symptoms = [
    {"head": ["dolor de cabeza", "jaqueca", "nauseas", "vomitos", "convulsiones"]},
    {"eyes": ["derrame", "vision nublada", "dolor de ojo", "fatiga visual", "punzadas"]},
    {"ears": ["dolor de oido", "perdida de audicion", "infeccion"]},
    {"nose": ["resfriado", "congestion nasal", "mucosidad"]},
    {"oralCavity": ["ulcera", "ulcera bucal", "ulcera", "afta", "fuego"]},
    {"neck": ["dolor de cuello", "dolor muscular", "rigidez", "punzadas", "dolor al tragar"]},
    {"chest": ["falta de aire", "dolor de pectoral", "presion"]},
    {"upperAbdomen": ["dolor", "dolor de costillas", "dolor en bazo"]},
    {"midAbdomen": ["dolor", "dolor de estomago", "punzadas"]},
    {"lowerAbdomen": ["dolor", "hinchazon"]},
    {"upperArm": ["moreton", "inflamacion", "dolor de articulacion"]},
    {"foreArm": ["inflamacion", "dolor articulacion"]},
    {"hands": ["inflamacion", "picazon", "dolor de articulaciones"]},
    {"sexualOrgans": ["picazon", "infeccion", "granos", "hinchazon"]},
    {"thighs": ["inflamacion", "color rojizo", "color morado"]},
    {"knees": ["dolor de articulacion", "inflamacion"]},
    {"lowerLeg": ["inflamacion", "color morado"]},
    {"foot": ["dolor de empeine", "dolor de talon", "dificultad para apoyar el pie"]}
]